name: GH Actions Cleanup

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:


jobs:
  cleanup:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate GH
        run: echo ${{secrets.GITHUB_TOKEN}} | gh auth login --with-token

      - name: Clean up
        run: ./ci/github-actions-storage-cleanup

